// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "moon",
    platforms: [
        .macOS(.v14),
        .iOS(.v17),
        .tvOS(.v17),
        .watchOS(.v10),
        .visionOS(.v1),
    ],
    products: [
        .executable(name: "moon", targets: ["MoonCLI"]),
        .library(name: "MoonAST", targets: ["MoonAST"]),
    ],
    targets: [
        .target(name: "MoonAST"),
        .target(name: "MoonTypes", dependencies: ["MoonAST"]),
        .target(name: "MoonLexer", dependencies: ["MoonAST"]),
        .target(name: "MoonParser", dependencies: ["MoonAST", "MoonLexer"]),
        .target(name: "MoonMoonfile"),
        .target(name: "MoonResolver", dependencies: ["MoonAST", "MoonParser", "MoonTypes", "MoonMoonfile"]),
        .target(name: "MoonTypechecker", dependencies: ["MoonAST", "MoonTypes", "MoonResolver"]),
        .target(name: "MoonSchemaCompiler", dependencies: ["MoonAST"]),
        .target(name: "MoonPlanner", dependencies: ["MoonAST"]),
        .target(name: "MoonBuild", dependencies: [
            "MoonAST",
            "MoonParser",
            "MoonTypechecker",
            "MoonPlanner",
            "MoonSchemaCompiler",
            "MoonResolver",
            "MoonMoonfile",
        ]),
        .target(name: "MoonRegistry", dependencies: ["MoonMoonfile"]),
        .target(name: "MoonFormatter", dependencies: ["MoonAST", "MoonParser"]),
        .target(name: "MoonLSP", dependencies: [
            "MoonAST",
            "MoonLexer",
            "MoonParser",
            "MoonTypechecker",
            "MoonResolver",
            "MoonFormatter",
            "MoonMoonfile",
        ]),
        .target(name: "MoonPrompt", dependencies: ["MoonAST", "MoonSchemaCompiler"]),
        .target(name: "MoonRuntime", dependencies: [
            "MoonAST",
            "MoonParser",
            "MoonResolver",
            "MoonPlanner",
            "MoonPrompt",
            "MoonSchemaCompiler",
            "MoonMoonfile",
        ]),
        .executableTarget(name: "MoonCLI", dependencies: [
            "MoonAST",
            "MoonLexer",
            "MoonParser",
            "MoonPlanner",
            "MoonTypechecker",
            "MoonMoonfile",
            "MoonBuild",
            "MoonRegistry",
            "MoonFormatter",
            "MoonLSP",
            "MoonRuntime",
        ]),
        .testTarget(name: "MoonASTTests", dependencies: ["MoonAST"]),
        .testTarget(name: "MoonToolchainTests", dependencies: [
            "MoonLexer", "MoonParser", "MoonTypechecker", "MoonResolver",
            "MoonMoonfile", "MoonPlanner", "MoonRuntime", "MoonBuild", "MoonSchemaCompiler",
            "MoonRegistry",
            "MoonFormatter",
            "MoonLSP",
            "MoonPrompt",
        ]),
    ]
)